# Generated by Django 5.2.6 on 2025-09-22 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='aim',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='school',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='school',
            name='social_links',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
