# Generated by Django 5.2.6 on 2025-09-24 10:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_profile_picture_user_school'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='user',
        #     name='school',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.school'),
        # ),
    ]
