# Generated by Django 5.2.6 on 2025-09-25 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_school'),
    ]

    # This migration is intentionally a no-op because the 'school' field
    # already exists on the User model (added in 0001_initial).
    # Leaving an empty operations list allows Django to mark it as applied
    # without altering the database schema.
    operations = []
