# Generated by Django 5.2.6 on 2025-09-25 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_school'),
    ]

    # This migration is intentionally a no-op because the 'school' field
    # is already present on the User model (added initially in 0001 and
    # reintroduced safely via raw SQL in 0004). Leaving operations empty
    # prevents duplicate column errors on fresh databases.
    operations = []
