# Generated by Django 5.2.6 on 2025-10-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_school_feature_flags_school_is_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
