# Generated by Django 5.2.6 on 2025-09-23 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_student_address_student_email_student_passport_no_and_more'),
        ('accounts', '0002_school_aim_school_logo_school_motto_and_more'),
        ('communications', '0002_event'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrearsMessageCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('min_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('send_in_app', models.BooleanField(default=True)),
                ('send_sms', models.BooleanField(default=False)),
                ('send_email', models.BooleanField(default=False)),
                ('email_subject', models.CharField(blank=True, default='', max_length=255)),
                ('sent_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('klass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.class')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrears_campaigns', to='accounts.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
