# Generated by Django 5.2.6 on 2025-09-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_arrearsmessagecampaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrearsmessagecampaign',
            name='error_message',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='arrearsmessagecampaign',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrearsmessagecampaign',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arrearsmessagecampaign',
            name='status',
            field=models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
    ]
