# Generated by Django on adding system_tag to Message
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0005_message_messagerecipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='system_tag',
            field=models.CharField(max_length=30, null=True, blank=True, db_index=True),
        ),
    ]
