# Generated by Django 5.2.6 on 2025-09-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0006_message_system_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrearsmessagecampaign',
            name='email_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arrearsmessagecampaign',
            name='email_sent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arrearsmessagecampaign',
            name='sms_failed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='arrearsmessagecampaign',
            name='sms_sent',
            field=models.IntegerField(default=0),
        ),
    ]
