version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-edutrack}
      POSTGRES_USER: ${POSTGRES_USER:-edutrack}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-edutrack}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: sh -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY:-dev}
      DEBUG: ${DEBUG:-True}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-*}
      CSRF_TRUSTED_ORIGINS: ${CSRF_TRUSTED_ORIGINS:-http://localhost}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      POSTGRES_DB: ${POSTGRES_DB:-edutrack}
      POSTGRES_USER: ${POSTGRES_USER:-edutrack}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-edutrack}
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      TIME_ZONE: ${TIME_ZONE:-Africa/Nairobi}
      CORS_ALLOW_ALL_ORIGINS: ${CORS_ALLOW_ALL_ORIGINS:-True}
      USE_S3: ${USE_S3:-False}
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL:-http://localhost:8000}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend
volumes:
  pgdata:
