services:
  - type: web
    name: edutrack-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn edutrack.wsgi:application
    plan: starter
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DEBUG
        value: "False"
      - key: USE_SQLITE
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        # After first deploy, set this to your Render service domain and any custom domains
        value: edutrack-backend.onrender.com,localhost,127.0.0.1
      - key: CSRF_TRUSTED_ORIGINS
        # Include backend + frontend domains (https). Update after setting domains.
        value: https://edutrack-backend.onrender.com,https://edutrack-frontend.netlify.app
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: https://edutrack-frontend.netlify.app
      - key: FRONTEND_URL
        value: https://edutrack-frontend.netlify.app
      - key: TIME_ZONE
        value: Africa/Nairobi
      - key: USE_S3
        value: "False"
      # S3/Spaces credentials (fill with your values)
      - key: AWS_ACCESS_KEY_ID
      - key: AWS_SECRET_ACCESS_KEY
      - key: AWS_STORAGE_BUCKET_NAME
      - key: AWS_S3_REGION_NAME
        value: us-east-1
      # If using DigitalOcean Spaces, set your endpoint (e.g., https://nyc3.digitaloceanspaces.com)
      - key: AWS_S3_ENDPOINT_URL
        value: 
      # Africa's Talking (optional)
      - key: AT_USERNAME
        value: sandbox
      - key: AT_API_KEY
        value: 
      - key: AT_SENDER_ID
        value: 
      - key: MESSAGES_QUEUE_DELIVERY
        value: "True"
      # Postgres wired from the managed database below
      - key: POSTGRES_HOST
        fromDatabase:
          name: edutrack-db
          property: host
      - key: POSTGRES_PORT
        fromDatabase:
          name: edutrack-db
          property: port
      - key: POSTGRES_USER
        fromDatabase:
          name: edutrack-db
          property: user
      - key: POSTGRES_PASSWORD
        fromDatabase:
          name: edutrack-db
          property: password
      - key: POSTGRES_DB
        fromDatabase:
          name: edutrack-db
          property: database

databases:
  - name: edutrack-db
    plan: starter
