# Generated by Django 5.2.6 on 2025-09-25 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_classsubjectteacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectGradingBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=5)),
                ('min', models.IntegerField()),
                ('max', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grading_bands', to='academics.subject')),
            ],
            options={
                'ordering': ['order', '-max'],
                'unique_together': {('subject', 'grade')},
            },
        ),
    ]
