# Generated by Django 5.2.6 on 2025-09-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_subjectgradingband'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exam',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
