# Generated by Django 5.2.6 on 2025-09-29 15:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_exam_published_exam_published_at'),
        ('accounts', '0007_user_school'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='class',
            options={'ordering': ['grade_level', 'stream__name'], 'verbose_name_plural': 'Classes'},
        ),
        migrations.AddField(
            model_name='class',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='class',
            name='grade_level',
            field=models.CharField(help_text="Grade level (e.g., '1', 'Grade 1')", max_length=20),
        ),
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='accounts.school'),
        ),
        migrations.AlterField(
            model_name='class',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.stream'),
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('grade_level', 'stream', 'school')},
        ),
    ]
