# Generated by Django 5.2.6 on 2025-10-01 21:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_room_timetableentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('max_marks', models.FloatField(blank=True, help_text='Optional max marks for this component', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Optional weight for aggregation (defaults to simple sum)', null=True)),
                ('order', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='academics.subject')),
            ],
            options={
                'ordering': ['subject', 'order', 'code'],
                'unique_together': {('subject', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='examresult',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subjectcomponent'),
        ),
        migrations.AlterUniqueTogether(
            name='examresult',
            unique_together={('exam', 'student', 'subject', 'component')},
        ),
    ]
