# Generated by Django 5.2.6 on 2025-10-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_teacheravailability_timetableplan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='can_manage_timetable',
            field=models.BooleanField(default=False, help_text='If true, this teacher can manage timetable data (create/update).'),
        ),
    ]
