# Generated by Django 5.2.6 on 2025-10-02 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_teacherprofile_can_manage_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableplan',
            name='block_assignments',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
