# Generated by Django 5.2.6 on 2025-10-02 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_timetableplan_block_assignments'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.CharField(choices=[('language', 'Language'), ('science', 'Science'), ('arts', 'Arts'), ('humanities', 'Humanities'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
