# Generated by Django 5.2.6 on 2025-10-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_subject_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_priority',
            field=models.BooleanField(default=False, help_text='If true, this subject is prioritized in timetable generation.'),
        ),
    ]
