# Generated by Django 5.2.6 on 2025-10-02 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_subject_is_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_plans', to='academics.term'),
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='week',
            field=models.IntegerField(blank=True, help_text='Week number within the term (1-13)', null=True),
        ),
    ]
