# Generated by Django 5.2.6 on 2025-10-10 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0020_lessonplan_term_lessonplan_week'),
        ('accounts', '0009_school_feature_flags_school_is_trial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='is_graduated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='accounts.school'),
        ),
    ]
