# Generated by Django 5.2.6 on 2025-10-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_student_graduation_year_student_is_graduated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='grade_level_tag',
            field=models.CharField(blank=True, db_index=True, help_text="Grade level at the time the exam was set (e.g., 'Grade 4')", max_length=20),
        ),
    ]
