# Generated by Django 5.2.6 on 2025-10-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_exam_grade_level_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['name', 'year', 'term', 'klass__grade_level', 'klass__stream__name', 'date', 'id']},
        ),
        migrations.AddField(
            model_name='student',
            name='upi_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
