# Generated by Django 5.2.6 on 2025-10-14 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_alter_exam_options_student_upi_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='is_examinable',
            field=models.BooleanField(default=True, help_text='If false, this subject is excluded from exams, results, and analytics.'),
        ),
    ]
