# Generated by Django 5.2.6 on 2025-10-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_subject_is_examinable'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='boarding_status',
            field=models.CharField(choices=[('day', 'Day'), ('boarding', 'Boarding')], default='day', help_text='Whether the student is a day scholar or a boarder.', max_length=10),
        ),
    ]
