# Generated by Django 5.2.6 on 2025-10-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_student_boarding_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birth_certificate_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_passport_no',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='tsc_number',
            field=models.CharField(blank=True, help_text='T.S.C number', max_length=50, null=True, unique=True),
        ),
    ]
