# Generated by Django 5.2.6 on 2025-09-22 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_invoice_term_invoice_year_feecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='payment_attachments/'),
        ),
    ]
