# Generated by Django 5.2.6 on 2025-09-23 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_school_aim_school_logo_school_motto_and_more'),
        ('finance', '0003_payment_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('mpesa', 'M-Pesa'), ('bank', 'Bank'), ('cash', 'Cash'), ('cheque', 'Cheque')], default='mpesa', max_length=20),
        ),
        migrations.CreateModel(
            name='MpesaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('short_code', models.CharField(help_text='Till or PayBill number', max_length=20)),
                ('passkey', models.CharField(help_text='Lipa Na Mpesa Online passkey', max_length=255)),
                ('callback_url', models.URLField(blank=True, help_text='Public HTTPS callback URL for STK push callbacks')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_config', to='accounts.school')),
            ],
            options={
                'verbose_name': 'Mpesa Configuration',
                'verbose_name_plural': 'Mpesa Configurations',
            },
        ),
    ]
