# Generated by Django 5.2.6 on 2025-10-15 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_pocketmoneywallet_pocketmoneytransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classfee',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
